"vpcId": "vpc-0ece9a0b3eda519e9"
"accountId": "756007437776"
"region": "ap-southeast-1"
"awsProfile": "default"

vpc:
  name: "demo"
  cidr: 10.23.0.0/16
  cidrMask: 28

scalingGroup: 
  - name: infra
    maxSize: 3
    minSize: 0
    desiredSize: 0
    outbound: true
    associatePublicIP: true
    instanceType: t3
    instanceSize: micro
    image: "ubuntu"
    subnetType: "public"